spring:
  application:
    name: auth-service
server:
  port: 8081
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_account_banking
    username: postgres
    password: 1111
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 10000ms
        acknowledge-mode: auto

rabbitmq:
  queue:
    update-info-account: 23130075-queue
    create-account: 23130075-create-account-queue
  exchange:
    update-info-account: 23130075-direct-exchange
    create-account: 23130075-create-account-exchange
  routing-key:
    update-info-account: 23130075-routing-key
    create-account: 23130075-create-account-routing-key

---
jwt:
  secretKey: 16502ee43b73ce88149ca42ab31db111063820asdbd106505a6sfsafg345ecbb33a7bbe6b38578b23baee473c7aaf89c8e490c8e1429fbb264f137d1e2b3fb2ef396d8
  accessTokenExpirationTime: 259200000 # 3 days
  refreshTokenExpirationTime: 2419200000 # 2 weeks
  resetPasswordTokenExpirationTime: 900000 # 15 minutes
---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka