spring:
  application:
    name: user-service
server:
  port: 8082
---
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_account_banking
    username: postgres
    password: 1111
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 10000ms
        acknowledge-mode: manual
---
logging:
  config: classpath:log4j2-spring.xml
---
grpc:
  client:
    parse-token:
      address: 'static://localhost:9090'
      negotiationType: plaintext
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka